// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJjdLxIZxee-KqacyWsm6McWom8DGspoA',
    appId: '1:3517621956:web:59f7a5049f99b3665ccb91',
    messagingSenderId: '3517621956',
    projectId: 'ecommercestacked',
    authDomain: 'ecommercestacked.firebaseapp.com',
    storageBucket: 'ecommercestacked.appspot.com',
    measurementId: 'G-MMYJMR792V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ4XzNO-RyGlLcgjv849TpTWcKHyO2ZyQ',
    appId: '1:3517621956:android:55499441051d10185ccb91',
    messagingSenderId: '3517621956',
    projectId: 'ecommercestacked',
    storageBucket: 'ecommercestacked.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADrdQchtOABX-fuvpKzKLAtEHvp3nhqDE',
    appId: '1:3517621956:ios:082369b36ac563455ccb91',
    messagingSenderId: '3517621956',
    projectId: 'ecommercestacked',
    storageBucket: 'ecommercestacked.appspot.com',
    iosBundleId: 'com.example.ecommerce_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADrdQchtOABX-fuvpKzKLAtEHvp3nhqDE',
    appId: '1:3517621956:ios:082369b36ac563455ccb91',
    messagingSenderId: '3517621956',
    projectId: 'ecommercestacked',
    storageBucket: 'ecommercestacked.appspot.com',
    iosBundleId: 'com.example.ecommerce_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJjdLxIZxee-KqacyWsm6McWom8DGspoA',
    appId: '1:3517621956:web:937ba7af240642795ccb91',
    messagingSenderId: '3517621956',
    projectId: 'ecommercestacked',
    authDomain: 'ecommercestacked.firebaseapp.com',
    storageBucket: 'ecommercestacked.appspot.com',
    measurementId: 'G-D12PEGKSG0',
  );
}
